version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/express/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: infrastructure/front/vue/Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge