services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/express/Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    env_file:
      - .env      

  frontend:
    build:
      context: ./infrastructure/front/vue
      dockerfile: Dockerfile
      target: production
    environment:
      - VITE_API_URL=${BACKEND_URL}
    depends_on:
      - backend