version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: infrastructure/express/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env      
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: infrastructure/front/vue/Dockerfile
      target: development
    ports:
      - "80:80"
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge